### ISSUE TITLE
Kotlin 2.0 Support

### ISSUE THREAD

**Issue by oboenikui** [suusan2go/kotlin-fill-class#128]
It has been announced that Kotlin 2.0 includes major changes to the compiler and IDEA plugin, so it probably won't work as is.

**Comment by oboenikui** [comment]
It doesn't work as I thought.

<img width="736" alt="image" src="https://github.com/suusan2go/kotlin-fill-class/assets/3191462/ec0e9dcd-747e-41ed-b45c-bf408ff39079">

**Comment by YaminMahdi** [comment]
![image](https://github.com/user-attachments/assets/f8710145-e2a4-494e-b2b6-4bc8ed47d130)

**Comment by HarukaYamamoto0** [comment]
So, any news? I thought this plugin was really cool, but before I could even test it, Android Studio complained, just like in the image.

> ![image](https://private-user-images.githubusercontent.com/48239104/371969958-f8710145-e2a4-494e-b2b6-4bc8ed47d130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjc5NTcsIm5iZiI6MTcyODI2NzY1NywicGF0aCI6Ii80ODIzOTEwNC8zNzE5Njk5NTgtZjg3MTAxNDUtZTJhNC00OTRlLWIyYjYtNGJjOGVkNDdkMTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAyMjA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNDgyMTBjNDkzYTkzY2QxNjNiY2Y2YTlhOTAxMGQ3ZWM3YTE5MjA3NjRjYTkzMTM0NDllMGMyZDA1NThkYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JmNUZ1N7-CRM2SuUEqBYdULKi8PiKW-H2-ymgP8hlzk)

**Comment by oboenikui** [comment]
Sorry for the wait. I am currently working on fixing minor issues.
Due to my busy day job, I am hoping to get a corrected release out in November.

**Comment by IvShilin** [comment]
> Sorry for the wait. I am currently working on fixing minor issues. Due to my busy day job, I am hoping to get a corrected release out in November.

Hi! Any updates?

**Comment by oboenikui** [comment]
Sorry, please wait a little longer. Most of the ported features have been implemented, but it will take a little longer to release because we have not been able to keep up with the changes in the JetBrains Marketplace.

**Comment by ArthurKun21** [comment]
Thank you, can finally check k2
