### ISSUE TITLE
Add k2 support

### ISSUE THREAD

**Issue by ColtonIdle** [suusan2go/kotlin-fill-class#131]
I updated my IDE setting to enable k2. After I restarted my IDE I got a warning to kotlin fill class isn't supported under k2. Would be great to have this back again!

**Comment by jisungbin** [comment]
Duplicated by #128

**Comment by orange-guo** [comment]
I have developed a plugin that only supports the K2 mode. You can download it from the [JetBrains Marketplace](https://plugins.jetbrains.com/plugin/25789-fill-kotlin-arguments).
