### ISSUE TITLE
Support installation for 2019.x versions of IntelliJ

### ISSUE THREAD

**Issue by WorkingDevel** [suusan2go/kotlin-fill-class#14]
With the current EAP of IDEA (2019.1 EAP) the plugin is not available in the plugin registry for installation. Please update the version requirements of the plugin to let it install on 2019.x builds.

**Comment by suusan2go** [comment]
@WorkingDevel I just published the plugin supports 2019.x builds. You can install it after JetBrains approval. it takes 1 or 2 days.

**Comment by WorkingDevel** [comment]
@suusan2go Thanks! Very fast reaction.
