### ISSUE TITLE
Android Studio 3.5 Canary 9でサポートエラー

### ISSUE THREAD

**Issue by Pluu** [suusan2go/kotlin-fill-class#15]
以下の画面のように表示されます
![image](https://user-images.githubusercontent.com/1534926/55298346-1fe5da00-5468-11e9-880a-512d53107b60.png)

**Comment by suusan2go** [comment]
最新版のビルドをサポートするように対応したものをリリースしました。
JetBrainsでのレビューが終わり次第ですが、大体2、3日で配信されると思います。
