### ISSUE TITLE
Can't get plugin work

### ISSUE THREAD

**Issue by vadim-shb** [suusan2go/kotlin-fill-class#18]
This plugin seems to be exactly what I'm looking for, but I can't get it work.
After Alt + Enter I can't see `Fill class constructor` option.

![image](https://user-images.githubusercontent.com/7152405/59339976-d63e2900-8d0d-11e9-9dff-d289ffc88cdb.png)

Environment:
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.9.0-9-amd64

**Comment by suusan2go** [comment]
@vadim-shb 
You can see `Fill class constructor` option !
![貼り付けた画像_2019_06_13_9_41](https://user-images.githubusercontent.com/8841470/59395573-9b94c900-8dbf-11e9-9f6f-8ab5f4cfd417.png)

`Fill class constructor` option was moved to `intention action` from `quick fix` at  #6 

I'll update the `gif`  image in README. thanks.

**Comment by vadim-shb** [comment]
Yeah... Sorry. I was kind of blind, while looked for it in another section. ￼￼
