### ISSUE TITLE
Double タイプの自動Fillエラー 

### ISSUE THREAD

**Issue by Pluu** [suusan2go/kotlin-fill-class#2]
Test 環境
- OS : macOS High Sierra 10.13.6
- IDE : Android Studio 3.3 Canary 5
- Kotlin : Kotlin 1.2.60
- Kotlin Fill Class : 0.1.4

- - -

Doubleタイプを指定すると `d`の文字が追加されます。
実際は`d`文字を消すのが正しいと思います。

![2018-08-08 2 28 04](https://user-images.githubusercontent.com/1534926/43817984-652d7d12-9b17-11e8-8b2d-090415585d59.png)

**Comment by suusan2go** [comment]
@Pluu 修正したものをリリースしました。早いと明日くらいには公開されると思います！
Thanks @naofumi-fujii  !
