### ISSUE TITLE
Make compatible with IntelliJ 2019.2.x

### ISSUE THREAD

**Issue by cgraupner-bm** [suusan2go/kotlin-fill-class#21]
With the current EAP of IDEA (2019.2.x) the plugin is not available in the plugin registry for installation. Please update the version requirements of the plugin to let it install on 2019.2.x builds.

**Comment by suusan2go** [comment]
@cgraupner-bm  I just published the plugin supports 2019.2 builds. You can install it after JetBrains approval. it takes 1 or 2 days.
