### ISSUE TITLE
Plugin not compatible with upcoming IntelliJ 2019.3

### ISSUE THREAD

**Issue by mgryszko** [suusan2go/kotlin-fill-class#30]
I cannot install the plugin because it is not listed for Intellij 2019.3 (currently in beta). Is it possible to release a new plugin version for the newest IntelliJ?

**Comment by toefel18** [comment]
Would love that as well, thanks for creating this

**Comment by suusan2go** [comment]
@mgryszko Sorry for late reply. I just published the plugin supports IntelliJ 2019.3. You can install it after JetBrains approval. it takes 1 or 2 days.

@toefel18 Thank you for contribution 🍺
