### ISSUE TITLE
Autocomplete parameter in new line format

### ISSUE THREAD

**Issue by ganjarpanji** [suusan2go/kotlin-fill-class#34]
Add capability to autocomplete each property on new line.
e.g 
![image](https://user-images.githubusercontent.com/1736817/71659798-724b8280-2d7b-11ea-9402-4197985f5753.png)

**Comment by suusan2go** [comment]
I think you can do it by the default Intention action below. Isn't this enough for you?
![image](https://user-images.githubusercontent.com/8841470/80273395-9eb15300-870c-11ea-9839-145cb200ff3b.png)

**Comment by ganjarpanji** [comment]
cool! thanks, i will close the issue :)

**Comment by Ghedeon** [comment]
While this is true that one can use default intention for separate lines, it's so common that I'm wondering how much of an effort would it be to add a corresponding checkbox to plugin configuration. A few repetitive clicks saved, still a win in my book!

**Comment by WildOrangutan** [comment]
Can we reopen this maybe? I would be nice to have a default behavior.
