### ISSUE TITLE
Incompatible with IntelliJ 2020.2 Update

### ISSUE THREAD

**Issue by mikemac42** [suusan2go/kotlin-fill-class#40]
![Screen Shot 2020-07-30 at 2 56 37 PM](https://user-images.githubusercontent.com/32336056/88968503-0c719b80-d275-11ea-95aa-c73b7fb5691c.png)

**Comment by suusan2go** [comment]
I just published v1.0.4 to the JetBrains marketplace. It will be available after their review finished.
