### ISSUE TITLE
Feature: Add option to use trailing comma

### ISSUE THREAD

**Issue by xsveda** [suusan2go/kotlin-fill-class#43]
Kotlin 1.4 supports trailing commas. They can be enabled in Idea's `Settings->Editor->Code Style->Kotlin->Other`.

It would be great if the plugin would respect the setting and generate trailing comma, so instead:
```
User(
  name = "",
  phone = "",
  address = ""
)
```
it would generate
```
User(
  name = "",
  phone = "",
  address = "",
)
```

**Comment by t-kameyama** [comment]
You can add trailing comma without option.

1. Check `User trailing comma`
<img width="746" alt="スクリーンショット 2021-02-11 7 48 41" src="https://user-images.githubusercontent.com/1121855/107583133-d6f33500-6c3d-11eb-9290-af6a033a0fa5.png">

2. Check `kotlin.formatter.allowTrailingCommaOnCallSite`
<img width="879" alt="スクリーンショット 2021-02-11 7 41 16" src="https://user-images.githubusercontent.com/1121855/107583148-dc507f80-6c3d-11eb-81ec-9b6babaef69e.png">
<img width="911" alt="スクリーンショット 2021-02-11 7 41 58" src="https://user-images.githubusercontent.com/1121855/107583160-e07c9d00-6c3d-11eb-9979-f1e5e4ce6537.png">

3. Fill class constructor
<img width="807" alt="スクリーンショット 2021-02-11 7 42 57" src="https://user-images.githubusercontent.com/1121855/107583178-e70b1480-6c3d-11eb-86e9-eb1d4fa5642e.png">
<img width="760" alt="スクリーンショット 2021-02-11 7 43 04" src="https://user-images.githubusercontent.com/1121855/107583184-e8d4d800-6c3d-11eb-98f7-8ee7d9027618.png">

4. Put arguments on separate lines
<img width="738" alt="スクリーンショット 2021-02-11 7 43 16" src="https://user-images.githubusercontent.com/1121855/107583191-eb373200-6c3d-11eb-97dc-3b6c3b3d79be.png">
<img width="726" alt="スクリーンショット 2021-02-11 7 43 26" src="https://user-images.githubusercontent.com/1121855/107583199-ed998c00-6c3d-11eb-892b-c5356a642d6d.png">

**Comment by xsveda** [comment]
Thank you @t-kameyama, works great!
