### ISSUE TITLE
Add support for IntelliJ IDEA 2020.3

### ISSUE THREAD

**Issue by MerkulovAA** [suusan2go/kotlin-fill-class#44]
Thanks for this nice plugin. The plugin doesn't work on 2020.3. Please add the support for this version.

**Comment by OttoColt** [comment]
We all often use this plugin. We need your support)).

**Comment by daincredibleholg** [comment]
Alright, this change should make CircleCI happy now. The plugin already works without any obvious issue in my local IntelliJ installation as well.
