### ISSUE TITLE
Add support for IJ 2021.1 EAP

### ISSUE THREAD

**Issue by sureshg** [suusan2go/kotlin-fill-class#46]
Plugin stopped working after upgrading to the latest EAP
```
IntelliJ IDEA 2021.1 EAP (Ultimate Edition)
Build #IU-211.4961.30, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1257.1 x86_64
macOS 10.15.7
```

**Comment by WorkingDevel** [comment]
A fork of this plugin here is now updated to work with IDEA 2021.*: https://github.com/DeveloperUtils/kotlin-function-arguments-helper/issues/2

**Comment by suusan2go** [comment]
Hi sorry for the late reply. I've  just released new version of this plugin that supports IDEA 2021.1.
