### ISSUE TITLE
Support IntelliJ 2021.2

### ISSUE THREAD

**Issue by csh0711** [suusan2go/kotlin-fill-class#52]
I really love the Kotlin Fill Class plugin, awesome work, thanks! 

Unfortunately after switching to IntelliJ 2021.2 the plugin isn't supported (yet?): 
:-( 

![image](https://user-images.githubusercontent.com/28889928/127670845-d7acb0a5-651c-4b34-af7c-adb0866c8bbb.png)

I would really appreciate if I can use it in IntelliJ 2021.2.

**Comment by suusan2go** [comment]
@csh0711 Thanks for raising this issue. I pushed the new version that supports IntelliJ 2021.2. It will be available soon once JetBrains finishes its review. Usually, it takes 1 or 2 business days.

**Comment by csh0711** [comment]
Works like a charm, thanks a lot! :-)
