### ISSUE TITLE
Support Android Studio Arctic Fox

### ISSUE THREAD

**Issue by ltiemon-kr** [suusan2go/kotlin-fill-class#54]
Hi, I've used this plug in, and I love it. It's extremely useful. But for a while now, it hasn't been compatible with android studio. I've tried to manually install it, as in the built in plugin viewer, the version is outdated (1.0.5). These are the build numbers for AS. Please let me know if you need anymore information.

Android Studio Arctic Fox | 2020.3.1 Patch 1
Build #AI-203.7717.56.2031.7621141, built on August 7, 2021

![image](https://user-images.githubusercontent.com/80338639/130144073-3089f956-900e-422a-8490-b96807fa1354.png)

**Comment by suusan2go** [comment]
@jfaq89 @ltiemon-kr Thank you for raising this. I found that there was a missing configuration to explicitly set the supported build. Therefore, it only supports the latest build of IDEA which is configured as `IntelliJ.version` in `build.gradle`. I fixed this in #55 and released it as 1.0.10. it should be available within two or three days. Let me know if you are still not able to install the latest version.
