### ISSUE TITLE
Not compatible with latest version of intellij  

### ISSUE THREAD

**Issue by xmlking** [suusan2go/kotlin-fill-class#59]
Not compatible with latest version of intellij  

<img width="703" alt="image" src="https://user-images.githubusercontent.com/627951/162668314-1a296a00-040f-45bb-aee1-18026968b1fd.png">

**Comment by JohNan** [comment]
I have opened a PR for this: https://github.com/suusan2go/kotlin-fill-class/pull/58 but @suusan2go have not approved it yet.

**Comment by suusan2go** [comment]
@xmlking thank you for raising this issue and sorry for the late reply. I published the latest plugin that supports 221. it should be available within 2 or 3 days.

@JohNan thank you for your PR. I pushed the changes to support 221.*. As I commented in the PR, I'm open to accepting your changes, but wanted to make the changes small as possible.
