### ISSUE TITLE
[Request] Put arguments on separate lines by default

### ISSUE THREAD

**Issue by WildOrangutan** [suusan2go/kotlin-fill-class#67]
Would it be possible to add a setting, to change default behavior how to "fill class constructor".

**Current behavior**
Currently when you fill a class, you get:
`User(name = "", surname = "", nickname = "")`

**Suggested behavior**
I would like to have a setting, when "fill class constructor" action is used, to fill it like this by default:
```
User(
    name = "", 
    surname = "", 
    nickname = ""
)
```

**Comment by WildOrangutan** [comment]
Hm, not sure if possible, but maybe it would be possible to run auto-format from IDE code style settings, after fill-action is used

**Comment by suusan2go** [comment]
Hi, I don't have time to look into the actual implementation, but I'm happy to add this feature to this plugin if you can create a PR 👍
