### ISSUE TITLE
Automate release process for new Idea versions

### ISSUE THREAD

**Issue by suusan2go** [suusan2go/kotlin-fill-class#71]
I'm not actively using Kotlin and IDEA these days, so it's hard for me to catch the new release in my daily work.
I know that waiting for my release to support the new version is a bit frustrating for the users who use the latest IDEA. Not sure it's possible, but I'm thinking of the process below.

- catch the new release of IDEA by cronjob (CircleCI or GitHub actions)
- update necessary information ref: https://github.com/suusan2go/kotlin-fill-class/commit/632ee2caae4a9ee4a0f1af3b035ecbdcd8e0cbd4
- create a new tag and publish the plugin if no tests fail.

Or if any configurations automatically make this plugin available on the new version, that would be ideal.

**Comment by suusan2go** [comment]
possibly just setting null to `untilBuild`  and removing `until-build` from `plugin.xml` would work

**Comment by oboenikui** [comment]
> possibly just setting null to untilBuild and removing until-build from plugin.xml would work

It looks like a good solution. It should be noted that the `updateSinceUntilBuild` option must be disabled.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010590059-Why-pluginUntilBuild-is-mandatory?page=1#community_comment_4407033276562
