### ISSUE TITLE
Fill with mock data option?

### ISSUE THREAD

**Issue by ColtonIdle** [suusan2go/kotlin-fill-class#88]
I love this plugin, but sometimes i Just want to mock something out and prefill with a bunch of fake data. Would be nice if instead of empty string it was just random chars, numbers, etc to stisfy the class construction. Would you be open to adding something like that?

**Comment by oboenikui** [comment]
Hello, thank you for your interest in this plugin. For this issue, you might be able to solve it with PR #88. It adds an option to generate random characters and numbers instead of empty strings. However, it is still lacking in tests. We are working on improving it and hope to merge it soon.
