### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tir38** [suusan2go/kotlin-fill-class#94]
Add option to put each arg on separate line. IntelliJ already has a separate keyboard shortcut to put args on a separate line, but it would be nice to do it all in one command.

**Comment by oboenikui** [comment]
Hi, @tir38. Thank you for your feature request.

There is already an option to "put arguments on separate lines".

Please see `Settings` > `Editor` > `Inspections` > `Kotlin` > `Fill class` on your IntelliJ.

Related PR: https://github.com/suusan2go/kotlin-fill-class/pull/75
